### ISSUE TITLE
Installation nicht möglich/Cannot be installed

### ISSUE THREAD

**Issue by TripleX1978** [gerbuchner/ioBroker.vis-owl#4]
**Describe the bug**  
Installation läuft nicht durch.

Folgendes wird angezeigt:

$ iobroker url iobroker.vis-owl --host ioBroker
install iobroker.vis-owl
NPM version: 6.14.16
Installing iobroker.vis-owl... (System call)

**Comment by gerbuchner** [comment]
Bitte komplette Fehlermeldung, sonst kann ich nichts machen. Danke

**Comment by TripleX1978** [comment]
Problem scheint sich erledigt zu haben.
Heute was der Adapter plötzlich installiert und läuft auch soweit.

**Comment by TripleX1978** [comment]
Ich hab da noch ein paar Fragen zur Aufteilung.
Wenn ich das richtig sehe, soll unter Betriebsmodus der Schalter für an/aus eingebunden werden und unter den Eigenschaften die Modi Kühlen, Heizen, Trocknen, Lüften und Auto?
Ist auch was vorgesehen für die Ventilatordrehzahl (Auto, Inneneinheit geräuscharm, manuell) und die Lamellenstellungen horizontal/vertikal (an, aus)?
Wäre es möglich die Oberfläche so zu verändern, dass man einen Schalter (an, aus) hat, in den Betriebsmodi dann Kühlen, Heizen etc. unterbringt und diese dann so angezeigt werden wie die Eigenschaften, also kein Pop-Up?
Unter Eigenschaften könnte man dann die Steuerung der Lamellen unterbringen.

Ansonsten finde ich das Widget echt klasse.

**Comment by gerbuchner** [comment]
Magst Du die Fragen bitte ins Forum https://forum.iobroker.net/topic/53045/test-widget-vis-owl-v0-2-x-github/331?loggedin=true kopieren? Haben jetzt ja nicht wirklich etwas mit einem Fehler zu tun und da tummeln sich noch andere Nutzer mit vielen Ideen ;)
